export const LEAD_FETCH_BEGIN = 'LEAD_FETCH_BEGIN'
export const LEAD_FETCH_SUCCESS = 'LEAD_FETCH_SUCCESS'
export const LEAD_FETCH_ERROR = 'LEAD_FETCH_ERROR'

export const SINGLELEAD_FETCH_BEGIN = 'SINGLELEAD_FETCH_BEGIN'
export const SINGLELEAD_FETCH_SUCCESS = 'SINGLELEAD_FETCH_SUCCESS'
export const SINGLELEAD_FETCH_ERROR = 'SINGLELEAD_FETCH_ERROR'

export const SINGLELEAD_DELETE = 'SINGLELEAD_DELETE'


