export const ADMIN_LOGIN_BEGIN = 'ADMIN_LOGIN_BEGIN'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR'

export const ADMIN_SIGNUP_BEGIN = 'ADMIN_SIGNUP_BEGIN'
export const ADMIN_SIGNUP_SUCCESS = 'ADMIN_SIGNUP_SUCCESS'
export const ADMIN_SIGNUP_ERROR = 'ADMIN_SIGNUP_ERROR'

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'
